/*
Copyright © 2018 Kyle Bai(kyle.b@inwinstack.com)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/inwinstack/ipam-operator/pkg/apis/inwinstack/v1"
	scheme "github.com/inwinstack/ipam-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PoolsGetter has a method to return a PoolInterface.
// A group's client should implement this interface.
type PoolsGetter interface {
	Pools() PoolInterface
}

// PoolInterface has methods to work with Pool resources.
type PoolInterface interface {
	Create(*v1.Pool) (*v1.Pool, error)
	Update(*v1.Pool) (*v1.Pool, error)
	UpdateStatus(*v1.Pool) (*v1.Pool, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Pool, error)
	List(opts metav1.ListOptions) (*v1.PoolList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Pool, err error)
	PoolExpansion
}

// pools implements PoolInterface
type pools struct {
	client rest.Interface
}

// newPools returns a Pools
func newPools(c *InwinstackV1Client) *pools {
	return &pools{
		client: c.RESTClient(),
	}
}

// Get takes name of the pool, and returns the corresponding pool object, and an error if there is any.
func (c *pools) Get(name string, options metav1.GetOptions) (result *v1.Pool, err error) {
	result = &v1.Pool{}
	err = c.client.Get().
		Resource("pools").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Pools that match those selectors.
func (c *pools) List(opts metav1.ListOptions) (result *v1.PoolList, err error) {
	result = &v1.PoolList{}
	err = c.client.Get().
		Resource("pools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pools.
func (c *pools) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("pools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a pool and creates it.  Returns the server's representation of the pool, and an error, if there is any.
func (c *pools) Create(pool *v1.Pool) (result *v1.Pool, err error) {
	result = &v1.Pool{}
	err = c.client.Post().
		Resource("pools").
		Body(pool).
		Do().
		Into(result)
	return
}

// Update takes the representation of a pool and updates it. Returns the server's representation of the pool, and an error, if there is any.
func (c *pools) Update(pool *v1.Pool) (result *v1.Pool, err error) {
	result = &v1.Pool{}
	err = c.client.Put().
		Resource("pools").
		Name(pool.Name).
		Body(pool).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *pools) UpdateStatus(pool *v1.Pool) (result *v1.Pool, err error) {
	result = &v1.Pool{}
	err = c.client.Put().
		Resource("pools").
		Name(pool.Name).
		SubResource("status").
		Body(pool).
		Do().
		Into(result)
	return
}

// Delete takes name of the pool and deletes it. Returns an error if one occurs.
func (c *pools) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("pools").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pools) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Resource("pools").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched pool.
func (c *pools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Pool, err error) {
	result = &v1.Pool{}
	err = c.client.Patch(pt).
		Resource("pools").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
