language: go
os: linux
sudo: required
services:
  - docker
go:
  - 1.11.x
go_import_path: github.com/inwinstack/ipam-operator

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
script:
  - make dep
  - make test
  - make
  - make build_image
  - make push_image
after_success:
  - bash <(curl -s https://codecov.io/bash)
