language: go
os: linux
sudo: required
services:
- docker
go:
- 1.11.x
go_import_path: github.com/inwinstack/ipam-operator
before_install:
- go get -u github.com/golang/dep/cmd/dep
script:
- make dep
- make test
- make
- bash <(curl -s https://codecov.io/bash)
after_success:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
- make build_image
- make push_image
