language: go
os: linux
sudo: required
services:
- docker
go:
- 1.12.x
go_import_path: github.com/inwinstack/ipam
env:
- GO111MODULE=on
script:
- go mod download
- make test
- make
after_success:
- bash <(curl -s https://codecov.io/bash)