/*
Copyright © 2018 Kyle Bai(kyle.b@inwinstack.com)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	inwinstackv1 "github.com/inwinstack/ipam-operator/pkg/apis/inwinstack/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePools implements PoolInterface
type FakePools struct {
	Fake *FakeInwinstackV1
}

var poolsResource = schema.GroupVersionResource{Group: "inwinstack.com", Version: "v1", Resource: "pools"}

var poolsKind = schema.GroupVersionKind{Group: "inwinstack.com", Version: "v1", Kind: "Pool"}

// Get takes name of the pool, and returns the corresponding pool object, and an error if there is any.
func (c *FakePools) Get(name string, options v1.GetOptions) (result *inwinstackv1.Pool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(poolsResource, name), &inwinstackv1.Pool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*inwinstackv1.Pool), err
}

// List takes label and field selectors, and returns the list of Pools that match those selectors.
func (c *FakePools) List(opts v1.ListOptions) (result *inwinstackv1.PoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(poolsResource, poolsKind, opts), &inwinstackv1.PoolList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &inwinstackv1.PoolList{ListMeta: obj.(*inwinstackv1.PoolList).ListMeta}
	for _, item := range obj.(*inwinstackv1.PoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pools.
func (c *FakePools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(poolsResource, opts))
}

// Create takes the representation of a pool and creates it.  Returns the server's representation of the pool, and an error, if there is any.
func (c *FakePools) Create(pool *inwinstackv1.Pool) (result *inwinstackv1.Pool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(poolsResource, pool), &inwinstackv1.Pool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*inwinstackv1.Pool), err
}

// Update takes the representation of a pool and updates it. Returns the server's representation of the pool, and an error, if there is any.
func (c *FakePools) Update(pool *inwinstackv1.Pool) (result *inwinstackv1.Pool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(poolsResource, pool), &inwinstackv1.Pool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*inwinstackv1.Pool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePools) UpdateStatus(pool *inwinstackv1.Pool) (*inwinstackv1.Pool, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(poolsResource, "status", pool), &inwinstackv1.Pool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*inwinstackv1.Pool), err
}

// Delete takes name of the pool and deletes it. Returns an error if one occurs.
func (c *FakePools) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(poolsResource, name), &inwinstackv1.Pool{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(poolsResource, listOptions)

	_, err := c.Fake.Invokes(action, &inwinstackv1.PoolList{})
	return err
}

// Patch applies the patch and returns the patched pool.
func (c *FakePools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *inwinstackv1.Pool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(poolsResource, name, data, subresources...), &inwinstackv1.Pool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*inwinstackv1.Pool), err
}
