apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pools.inwinstack.com
spec:
  group: inwinstack.com
  version: v1
  names:
    kind: Pool
    plural: pools
  scope: Cluster
  additionalPrinterColumns:
  - name: Allocatable
    type: integer
    JSONPath: .status.allocatable
  - name: Capacity
    type: integer
    JSONPath: .status.capacity
  - name: Status
    type: string
    JSONPath: .status.phase
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ips.inwinstack.com
spec:
  group: inwinstack.com
  version: v1
  names:
    kind: IP
    plural: ips
  scope: Namespaced
  additionalPrinterColumns:
  - name: Address
    type: string
    JSONPath: .status.address
  - name: Status
    type: string
    JSONPath: .status.phase
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp