apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipam
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ipam
  template:
    metadata:
      labels:
        k8s-app: ipam
    spec:
      priorityClassName: system-cluster-critical
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      serviceAccountName: ipam
      containers:
      - name: ipam
        image: inwinstack/ipam:v0.6.1
        args:
        - --logtostderr=true
        - --v=2
