apiVersion: v1
kind: ServiceAccount
metadata:
  name: ipam
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ipam-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - inwinstack.com
  resources:
  - "*"
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ipam-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ipam-role
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: ipam