apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipam-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipam
  template:
    metadata:
      labels:
        app: ipam
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      serviceAccountName: ipam
      containers:
      - name: ipam-controller
        image: inwinstack/ipam:v0.4.1
        args:
        - --logtostderr=true
        - --default-ignore-namespaces=kube-system,default,kube-public 
        - --default-address=172.22.132.150-172.22.132.200
        - --default-auto-assign=true
        - --default-ignore-annotation=false
        - --v=2