apiVersion: inwinstack.com/v1
kind: Pool
metadata:
  name: default
spec:
  address: 172.22.132.200-172.22.132.230
  ignoreNamespaceAnnotation: false
  autoAssignToNamespace: true
  ignoreNamespaces:
  - kube-system
  - kube-public
  - default
  
