apiVersion: inwinstack.com/v1
kind: Pool
metadata:
  name: internet
spec:
  address: 104.145.33.128/25 
  ignoreNamespaceAnnotation: true
  autoAssignToNamespace: false
  ignoreNamespaces:
  - kube-system
  - kube-public
  - default
  
