apiVersion: inwinstack.com/v1
kind: Pool
metadata:
  name: test
spec:
  addresses: 
  - 172.22.132.0-172.22.132.10
  - 172.22.132.250-172.22.132.255
  assignToNamespace: false
  avoidBuggyIPs: true
  avoidGatewayIPs: true
  ignoreNamespaces:
  - kube-system
  - kube-public
  - default
